stations = ['Admiralty', 'Aljunied', 'Ang Mo Kio', 'Bartley', 'Bedok', 'Bishan', 'Boon Keng', 'Boon Lay', 'Braddell',
            'Bras Basah', 'Buangkok', 'Bugis', 'Bukit Batok', 'Bukit Gombak', 'Buona Vista', 'Canberra', 'Changi Airport',
            'Chinatown', 'Chinese Garden', 'Choa Chu Kang', 'City Hall', 'Clarke Quay', 'Clementi', 'Commonwealth', 'Dakota',
            'Dhoby Ghaut', 'Dover', 'Esplanade', 'Eunos', 'Expo', 'Farrer Park', 'HarbourFront', 'Hougang', 'Joo Koon',
            'Jurong East', 'Kallang', 'Kembangan', 'Khatib', 'Kovan', 'Kranji', 'Lakeside', 'Lavender', 'Little India',
            'Lorong Chuan', 'MacPherson', 'Marina Bay', 'Marina South Pier', 'Marsiling', 'Marymount', 'Mountbatten',
            'Newton', 'Nicoll Highway', 'Novena', 'Orchard', 'Outram Park', 'Pasir Ris', 'Paya Lebar', 'Pioneer',
            'Potong Pasir', 'Promenade', 'Punggol', 'Queenstown', 'Raffles Place', 'Redhill', 'Sembawang', 'Sengkang',
            'Serangoon', 'Simei', 'Somerset', 'Stadium', 'Tai Seng', 'Tampines', 'Tanah Merah', 'Tanjong Pagar',
            'Tiong Bahru', 'Toa Payoh', 'Woodlands', 'Woodleigh', 'Yew Tee', 'Yio Chu Kang', 'Yishun']

station_to_index = {station: i for i, station in enumerate(stations)}

initial_adjacency_dict = {'Jurong East': [('Bukit Batok', 1), ('Clementi', 1), ('Chinese Garden', 1)],
                          'Bukit Batok': [('Jurong East', 1), ('Bukit Gombak', 1)],
                          'Bukit Gombak': [('Bukit Batok', 1), ('Choa Chu Kang', 1)],
                          'Choa Chu Kang': [('Bukit Gombak', 1), ('Yew Tee', 1)],
                          'Yew Tee': [('Choa Chu Kang', 1), ('Kranji', 1)],
                          'Kranji': [('Yew Tee', 1), ('Marsiling', 1)],
                          'Marsiling': [('Kranji', 1), ('Woodlands', 1)],
                          'Woodlands': [('Marsiling', 1), ('Admiralty', 1)],
                          'Admiralty': [('Woodlands', 1), ('Sembawang', 1)],
                          'Sembawang': [('Admiralty', 1), ('Canberra', 1)],
                          'Canberra': [('Sembawang', 1), ('Yishun', 1)],
                          'Yishun': [('Canberra', 1), ('Khatib', 1)],
                          'Khatib': [('Yishun', 1), ('Yio Chu Kang', 1)],
                          'Yio Chu Kang': [('Khatib', 1), ('Ang Mo Kio', 1)],
                          'Ang Mo Kio': [('Yio Chu Kang', 1), ('Bishan', 1)],
                          'Bishan': [('Ang Mo Kio', 1), ('Braddell', 1), ('Lorong Chuan', 1), ('Marymount', 1)],
                          'Braddell': [('Bishan', 1), ('Toa Payoh', 1)],
                          'Toa Payoh': [('Braddell', 1), ('Novena', 1)],
                          'Novena': [('Toa Payoh', 1), ('Newton', 1)],
                          'Newton': [('Novena', 1), ('Orchard', 1)],
                          'Orchard': [('Newton', 1), ('Somerset', 1)],
                          'Somerset': [('Orchard', 1), ('Dhoby Ghaut', 1)],
                          'Dhoby Ghaut': [('Somerset', 1), ('City Hall', 1), ('Clarke Quay', 1), ('Little India', 1), ('Bras Basah', 1)],
                          'City Hall': [('Dhoby Ghaut', 1), ('Raffles Place', 1), ('Bugis', 1), ('Raffles Place', 1)],
                          'Raffles Place': [('City Hall', 1), ('Marina Bay', 1), ('City Hall', 1), ('Tanjong Pagar', 1)],
                          'Marina Bay': [('Raffles Place', 1), ('Marina South Pier', 1)],
                          'Marina South Pier': [('Marina Bay', 1)],
                          'Pasir Ris': [('Tampines', 1)],
                          'Tampines': [('Pasir Ris', 1), ('Simei', 1)],
                          'Simei': [('Tampines', 1), ('Tanah Merah', 1)],
                          'Tanah Merah': [('Simei', 1), ('Bedok', 1), ('Expo', 1)],
                          'Bedok': [('Tanah Merah', 1), ('Kembangan', 1)],
                          'Kembangan': [('Bedok', 1), ('Eunos', 1)],
                          'Eunos': [('Kembangan', 1), ('Paya Lebar', 1)],
                          'Paya Lebar': [('Eunos', 1), ('Aljunied', 1), ('Dakota', 1), ('MacPherson', 1)],
                          'Aljunied': [('Paya Lebar', 1), ('Kallang', 1)],
                          'Kallang': [('Aljunied', 1), ('Lavender', 1)],
                          'Lavender': [('Kallang', 1), ('Bugis', 1)],
                          'Bugis': [('Lavender', 1), ('City Hall', 1)],
                          'Tanjong Pagar': [('Raffles Place', 1), ('Outram Park', 1)],
                          'Outram Park': [('Tanjong Pagar', 1), ('Tiong Bahru', 1), ('HarbourFront', 1), ('Chinatown', 1)],
                          'Tiong Bahru': [('Outram Park', 1), ('Redhill', 1)],
                          'Redhill': [('Tiong Bahru', 1), ('Queenstown', 1)],
                          'Queenstown': [('Redhill', 1), ('Commonwealth', 1)],
                          'Commonwealth': [('Queenstown', 1), ('Buona Vista', 1)],
                          'Buona Vista': [('Commonwealth', 1), ('Dover', 1)],
                          'Dover': [('Buona Vista', 1), ('Clementi', 1)],
                          'Clementi': [('Dover', 1), ('Jurong East', 1)],
                          'Chinese Garden': [('Jurong East', 1), ('Lakeside', 1)],
                          'Lakeside': [('Chinese Garden', 1), ('Boon Lay', 1)],
                          'Boon Lay': [('Lakeside', 1), ('Pioneer', 1)],
                          'Pioneer': [('Boon Lay', 1), ('Joo Koon', 1)],
                          'Joo Koon': [('Pioneer', 1)],
                          'Expo': [('Tanah Merah', 1), ('Changi Airport', 1)],
                          'Changi Airport': [('Expo', 1)],
                          'HarbourFront': [('Outram Park', 1)],
                          'Chinatown': [('Outram Park', 1), ('Clarke Quay', 1)],
                          'Clarke Quay': [('Chinatown', 1), ('Dhoby Ghaut', 1)],
                          'Little India': [('Dhoby Ghaut', 1), ('Farrer Park', 1)],
                          'Farrer Park': [('Little India', 1), ('Boon Keng', 1)],
                          'Boon Keng': [('Farrer Park', 1), ('Potong Pasir', 1)],
                          'Potong Pasir': [('Boon Keng', 1), ('Woodleigh', 1)],
                          'Woodleigh': [('Potong Pasir', 1), ('Serangoon', 1)],
                          'Serangoon': [('Woodleigh', 1), ('Kovan', 1), ('Bartley', 1), ('Lorong Chuan', 1)],
                          'Kovan': [('Serangoon', 1), ('Hougang', 1)],
                          'Hougang': [('Kovan', 1), ('Buangkok', 1)],
                          'Buangkok': [('Hougang', 1), ('Sengkang', 1)],
                          'Sengkang': [('Buangkok', 1), ('Punggol', 1)],
                          'Punggol': [('Sengkang', 1)],
                          'Bras Basah': [('Dhoby Ghaut', 1), ('Esplanade', 1)],
                          'Esplanade': [('Bras Basah', 1), ('Promenade', 1)],
                          'Promenade': [('Esplanade', 1), ('Nicoll Highway', 1)],
                          'Nicoll Highway': [('Promenade', 1), ('Stadium', 1)],
                          'Stadium': [('Nicoll Highway', 1), ('Mountbatten', 1)],
                          'Mountbatten': [('Stadium', 1), ('Dakota', 1)],
                          'Dakota': [('Mountbatten', 1), ('Paya Lebar', 1)],
                          'MacPherson': [('Paya Lebar', 1), ('Tai Seng', 1)],
                          'Tai Seng': [('MacPherson', 1), ('Bartley', 1)],
                          'Bartley': [('Tai Seng', 1), ('Serangoon', 1)],
                          'Lorong Chuan': [('Serangoon', 1), ('Bishan', 1)],
                          'Marymount': [('Bishan', 1)]}

adjacency_list = [[(station_to_index[station], wt) for station, wt in initial_adjacency_dict[source]] for source in stations]

links = 0
for li in adjacency_list:
    links += len(li)
links = links // 2
print(links)
